# Generated by Django 3.1.7 on 2021-08-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20210729_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img/'),
        ),
    ]
