# Generated by Django 3.1.7 on 2021-08-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_about_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='background',
        ),
    ]
